### ISSUE TITLE
new focus & direction

### ISSUE THREAD

**Issue by ahmadnassri** [devconfig/discussion#1]
prior to our last event we discussed refocusing the group towards more a generic topic that's language / platform agnostic.

The general theme is around tooling, automation and developer workflow.

##### TODO 

- [ ] new name
- [ ] new blurb
- [ ] new logo

**Comment by ahmadnassri** [comment]
some ideas for the name: 

- `Dev Flow`
- `Totally Tooling` *(totally stealing that from [Addy's show](https://www.youtube.com/playlist?list=PLOU2XLYxmsILKwwASNS0xgfcmakbK_8JZ))*

**Comment by pearlchen** [comment]
correction: Addy and Matt's show :)

* flow
* d.flow
* tips, tools, and trade secretes (tx3)
* work it
* w0rk
* code flow

(gosh, I'm bad at naming things.)

**Comment by tomcreighton** [comment]
* Toolkit (... Devkit / Buildkit)
* Construct (noun _and_ verb meaning!)

**Comment by ahmadnassri** [comment]
I like "DevKit"

**Comment by ahmadnassri** [comment]
![image](https://cloud.githubusercontent.com/assets/183195/8689449/b1c09efe-2a75-11e5-8198-6ad70f54f3ad.png)

**Comment by ahmadnassri** [comment]
playing around with logo ideas:

![image](https://cloud.githubusercontent.com/assets/183195/8689672/cf3cffc4-2a78-11e5-949b-62b304d09d9f.png)

**Comment by ahmadnassri** [comment]
![image](https://cloud.githubusercontent.com/assets/183195/8728607/1866cacc-2bb4-11e5-954a-7f684a65b1af.png)
